ALTER TABLE jobs ADD COLUMN relevant INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN salary_min INTEGER;
ALTER TABLE jobs ADD COLUMN salary_max INTEGER;
ALTER TABLE jobs ADD COLUMN education TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN required_skills TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN preferred_skills TEXT NOT NULL DEFAULT '[]';
ALTER TABLE jobs ADD COLUMN skills TEXT NOT NULL DEFAULT '[]';